import { bullets, doc, paragraph, prose } from './richtext'

/**
 * SEED DATA — placeholder records carried over from the approved prototype.
 * Everything here is editable at /admin; replace before publishing.
 */
export const projects = [
  {
    title: 'Sanct E2E Messaging',
    slug: 'sanct-e2e-messaging',
    summary: 'Signal-protocol encryption layer — X3DH, Double Ratchet and ChaCha20-Poly1305 at scale.',
    category: 'Encryption',
    year: 2026,
    subtag: 'RUST',
    tags: ['RUST', 'CRYPTO', 'X3DH'],
    weight: 5,
    featured: true,
    featuredOrder: 1,
    mosaicSpan: '4',
    stripArtwork: 'vault',
    description: doc(
      paragraph(
        'An end-to-end encryption layer built on the Signal Protocol: X3DH key agreement, Double Ratchet session state and ChaCha20-Poly1305 payload encryption, wrapped in a transport-agnostic Rust core.',
      ),
      bullets([
        'Forward secrecy and post-compromise security verified against the protocol spec.',
        'Session state persisted through a pluggable store so the core stays transport-agnostic.',
        'Benchmarked for message throughput under sustained multi-device fan-out.',
      ]),
    ),
    links: [{ label: 'GITHUB', url: 'https://github.com/' }],
  },
  {
    title: 'RedOps Collab',
    slug: 'redops-collab',
    summary: 'Collaborative red-team operations platform — scoping, finding logs and report generation.',
    category: 'Platform',
    year: 2026,
    subtag: 'NEXT.JS',
    tags: ['NEXT.JS', 'POSTGRES', 'SECURITY'],
    weight: 5,
    featured: true,
    featuredOrder: 2,
    mosaicSpan: 'auto',
    stripArtwork: 'lattice',
    description: prose(
      'A workspace for red-team engagements: scope definition, evidence-linked finding logs, and report generation that turns a running engagement into a deliverable without a copy-paste pass.',
      'Built around the observation that most engagement time is lost to writing up work that was already documented once, badly, in a chat thread.',
    ),
    links: [{ label: 'GITHUB', url: 'https://github.com/' }],
  },
  {
    title: 'LLM Pentest Research',
    slug: 'llm-pentest-research',
    summary: 'Academic research into agentic LLM workflows for automated penetration testing.',
    category: 'Research',
    year: 2026,
    subtag: 'LLM',
    tags: ['LLM', 'SECURITY', 'RESEARCH'],
    weight: 4,
    featured: true,
    featuredOrder: 3,
    mosaicSpan: 'auto',
    stripArtwork: 'radar',
    description: prose(
      'Ongoing research into how far agentic LLM workflows can carry a penetration test before a human has to take over, and what the failure modes look like when they do.',
      'The interesting result so far is not capability but calibration: models are far more willing to declare a finding than to declare uncertainty.',
    ),
    links: [],
  },
  {
    title: 'OptiWealth',
    slug: 'optiwealth',
    summary: 'Predictive personal-finance platform. PM on a five-person founding team under EFN UGM.',
    category: 'Product',
    year: 2026,
    subtag: 'ML',
    tags: ['ML', 'FINTECH', 'PM'],
    weight: 4,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'skyline',
    description: prose(
      'A predictive personal-finance platform built under EFN UGM. I ran product on a five-person founding team: scope, roadmap, and the arguments about what not to build.',
    ),
    links: [],
  },
  {
    title: 'Cloud Library',
    slug: 'cloud-library',
    summary: 'Interactive portfolio built around a navigable 3D library — the study that seeded this site.',
    category: 'Interface',
    year: 2025,
    subtag: 'THREE.JS',
    tags: ['THREE.JS', 'UX', 'WEBGL'],
    weight: 4,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'tower',
    description: prose(
      'A portfolio concept navigated as a 3D library rather than a page. It answered the question this site is built on: whether a spatial metaphor can carry real content without becoming a toy.',
    ),
    links: [],
  },
  {
    title: 'BHOB UX Audit',
    slug: 'bhob-ux-audit',
    summary: 'Live UX audit and digital-infrastructure roadmap for an e-commerce client under 180DC UGM.',
    category: 'Consulting',
    year: 2026,
    subtag: 'UX',
    tags: ['UX', 'CONSULTING', 'E-COMMERCE'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'bridge',
    description: prose(
      'A live UX audit for Bumi Herbs Oditi Bali, delivered under 180 Degrees Consulting UGM: heuristic review of the storefront, funnel instrumentation gaps, and a staged roadmap for the digital infrastructure behind it.',
    ),
    links: [],
  },
  {
    title: 'SIMRS Cloud Migration',
    slug: 'simrs-cloud-migration',
    summary: 'Migration architecture for a hospital information system: LAMP to AWS, with cost modelling.',
    category: 'Cloud',
    year: 2025,
    subtag: 'AWS',
    tags: ['AWS', 'CLOUD', 'ARCHITECTURE'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'lattice',
    description: prose(
      'A migration proposal for SIMRS Khanza: moving a LAMP-stack hospital information system to AWS, with a cost model that made the trade-offs legible to non-technical decision makers.',
    ),
    links: [],
  },
  {
    title: 'Solar Pilot Advisory',
    slug: 'solar-pilot-advisory',
    summary: 'Risk register, roadmap and replication triggers for an NGO community-solar pilot.',
    category: 'Strategy',
    year: 2026,
    subtag: 'STRATEGY',
    tags: ['STRATEGY', 'ENERGY', 'CASE'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'radar',
    description: prose(
      'A case submission built around a community-solar pilot: risk register, phased roadmap, and explicit replication triggers so the NGO would know when the pilot had earned a second site.',
    ),
    links: [],
  },
  {
    title: 'CTF Writeup Engine',
    slug: 'ctf-writeup-engine',
    summary: 'Static pipeline turning raw challenge notes into publishable write-ups.',
    category: 'Tooling',
    year: 2026,
    subtag: 'TOOLING',
    tags: ['TOOLING', 'MARKDOWN', 'CI'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'bridge',
    description: prose(
      'The notes you take while solving a challenge and the write-up you publish afterwards are almost the same document. This pipeline closes the gap: annotated notes in, formatted write-up out, no second pass.',
    ),
    links: [],
  },
  {
    title: 'Sleep Clustering',
    slug: 'sleep-clustering',
    summary: 'Unsupervised clustering of sleep-efficiency data with ANOVA validation.',
    category: 'Data',
    year: 2025,
    subtag: 'K-MEANS',
    tags: ['K-MEANS', 'PCA', 'PYTHON'],
    weight: 2,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'skyline',
    description: prose(
      'K-Means, DBSCAN and PCA over a sleep-efficiency dataset, with ANOVA used to check that the clusters separated on something other than noise.',
    ),
    links: [],
  },
  {
    title: 'Deck Forge',
    slug: 'deck-forge',
    summary: 'Reusable consulting-deck generation pipeline built across 180DC engagements.',
    category: 'Tooling',
    year: 2026,
    subtag: 'PPTXGENJS',
    tags: ['PPTXGENJS', 'AUTOMATION'],
    weight: 2,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'lattice',
    description: prose(
      'Consulting decks are 80% layout and 20% argument. This generates the 80% from structured content so the remaining time goes to the argument.',
    ),
    links: [],
  },
  {
    title: 'LFSR Toolkit',
    slug: 'lfsr-toolkit',
    summary: 'Stream-cipher and classical-cipher analysis utilities written in C.',
    category: 'Cryptography',
    year: 2025,
    subtag: 'CRYPTO',
    tags: ['CRYPTO', 'C', 'LFSR'],
    weight: 2,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'vault',
    description: prose(
      'Linear-feedback shift register analysis plus a set of classical-cipher breakers, written in C to keep the bit manipulation honest.',
    ),
    links: [],
  },
  {
    title: 'GNFA Visualizer',
    slug: 'gnfa-visualizer',
    summary: 'Interactive state-elimination visualiser for generalised NFAs.',
    category: 'Theory',
    year: 2025,
    subtag: 'AUTOMATA',
    tags: ['AUTOMATA', 'THEORY', 'VIZ'],
    weight: 2,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'lattice',
    description: prose(
      'State elimination is easy to describe and hard to follow on a whiteboard. This shows each elimination step and the regular expression growing out of it.',
    ),
    links: [],
  },
  {
    title: 'Spline Lab',
    slug: 'spline-lab',
    summary: 'Numerical-methods notebooks: cubic splines, Newton-Raphson, LU decomposition.',
    category: 'Numerics',
    year: 2025,
    subtag: 'NUMERICS',
    tags: ['NUMERICS', 'PYTHON'],
    weight: 1,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'radar',
    description: prose(
      'Interactive study notebooks for a numerical methods course — cubic splines, Newton-Raphson and LU decomposition, each with the failure cases left in.',
    ),
    links: [],
  },
] as const
