import { bullets, doc, heading, paragraph, prose } from './richtext'

/**
 * Real projects, taken from github.com/Shazaw plus the two engagements that
 * have no repository. `screenshot` names a file in /seed-assets, captured from
 * the running project (or downloaded from the repo where the author already
 * published one); the seed uploads it into Payload media. It is optional — a
 * project without one falls back to generated wireframe artwork.
 */
export const projects = [
  {
    title: 'NetGuard',
    slug: 'netguard-pcap-analysis',
    summary:
      'Full-stack PCAP analyser that detects SQL injection, XSS, port scans and suspicious payloads, then scores them against MITRE ATT&CK.',
    category: 'Security Tooling',
    year: 2025,
    subtag: 'FLASK',
    tags: ['Python', 'Flask', 'SQLite', 'React', 'Vite', 'Recharts', 'Framer Motion', 'Scapy'],
    weight: 5,
    featured: true,
    featuredOrder: 1,
    mosaicSpan: '4',
    stripArtwork: 'radar',
    repoUrl: 'https://github.com/Shazaw/PCAP-Analysis-Tool',
    screenshot: 'netguard-dashboard.png',
    description: doc(
      paragraph(
        'A network packet analyser that turns a capture file into an answer. NetGuard parses .pcap, .pcapng and .cap files, classifies the traffic, and surfaces what actually deserves attention rather than dumping every packet on the analyst.',
      ),
      heading('Detection'),
      bullets([
        'SQL injection, XSS and command injection in payloads.',
        'Port scanning, with the scanned port list reconstructed.',
        'Encrypted traffic flagged as a potential exfiltration channel.',
      ]),
      heading('Triage'),
      bullets([
        'Automated risk scoring with HIGH / MEDIUM / LOW severity bands.',
        'MITRE ATT&CK tactic and technique mapping on every alert.',
        'Deep packet inspection with hex and ASCII dumps, and scan history.',
      ]),
    ),
  },
  {
    title: 'AutoSIEM',
    slug: 'autosiem',
    summary:
      'SIEM prototype pairing an XGBoost fraud classifier with Gemini-generated incident summaries. Honorable Mention, UGM DCSE Summer Course 2025.',
    category: 'Machine Learning',
    year: 2025,
    subtag: 'XGBOOST',
    tags: ['Python', 'XGBoost', 'Optuna', 'Jupyter', 'Gemini API', 'Pandas', 'Figma'],
    weight: 5,
    featured: true,
    featuredOrder: 2,
    mosaicSpan: 'auto',
    stripArtwork: 'lattice',
    repoUrl: 'https://github.com/Farscent/AUTOSIEM',
    screenshot: 'autosiem-4.png',
    description: doc(
      paragraph(
        'Traditional SIEM tooling leans on hand-written rules and an analyst with time to read them. AutoSIEM automates the first pass: a model finds the fraud, and generative AI writes the summary a human would otherwise have to assemble.',
      ),
      bullets([
        'XGBoost classifier tuned with Optuna over 6.3M financial transactions, ~99.9% accuracy with few false positives.',
        'Behavioural analytics for account draining, out-of-hours activity spikes and repeat offenders.',
        'Gemini API generates the fraud alerts and reconstructs attack timelines in plain language.',
        'Splunk-inspired SOC dashboard: KPIs, fraud-by-hour breakdowns, live alerts and drilldown tables.',
      ]),
      paragraph('Built during the UGM DCSE Summer Course 2025, where it received an Honorable Mention.'),
    ),
  },
  {
    title: 'AeroRoute Lab',
    slug: 'aeroroute-pentest-lab',
    summary:
      'Containerised black-box pentest final: a fictional drone-logistics platform with twelve findings that chain from DNS enumeration to root.',
    category: 'Security Education',
    year: 2026,
    subtag: 'DOCKER',
    tags: ['TypeScript', 'React', 'Vite', 'Three.js', 'Docker', 'Nginx', 'BIND9', 'Shell'],
    weight: 5,
    featured: true,
    featuredOrder: 3,
    mosaicSpan: 'auto',
    stripArtwork: 'bridge',
    repoUrl: 'https://github.com/Shazaw/Pentesting-Evaluation-Lab-2026',
    screenshot: 'aeroroute.png',
    description: doc(
      paragraph(
        'A full evaluation environment built as a believable product rather than a checklist: a public website, an operator console, an API and a handful of network services, all containerised and resettable between sessions.',
      ),
      paragraph(
        'Twelve intended findings chain from unauthenticated enumeration through to root on the isolated lab host — DNS zone transfer, a leaked .env on a guest SMB share, SSH credential reuse, an incident IDOR, UNION SQL injection, and a SUID PATH hijack at the end. Each is gated by a flag so instructors can enable individual paths.',
      ),
      paragraph(
        'Ships with an architecture and containment note, a student brief, a grading rubric and an instructor answer key in which every step was executed live against a deployed instance.',
      ),
    ),
  },
  {
    title: 'RedOps Collab',
    slug: 'redops-collab',
    summary:
      'Penetration-testing collaboration platform: engagement scoping, evidence-linked findings and report generation, with session auth and MFA.',
    category: 'Platform',
    year: 2026,
    subtag: 'FASTIFY',
    tags: ['TypeScript', 'React', 'Vite', 'Fastify', 'PostgreSQL', 'Redis', 'MinIO', 'Docker'],
    weight: 4,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'lattice',
    repoUrl: 'https://github.com/Shazaw/WIRPL-Group-Project-RedOps',
    screenshot: 'redops-app.png',
    description: prose(
      'A workspace for red-team engagements, built as a TypeScript monorepo: a React front end preserving the original terminal-styled prototype, a Fastify API with session auth, an MFA flow and audit events, and shared contracts between them.',
      'Most engagement time is lost re-writing work that was already documented once, badly, in a chat thread. The operations dashboard keeps engagements, findings and sign-off state in one place so the report is a by-product rather than a second job.',
    ),
  },
  {
    title: 'CloudLibrary',
    slug: 'cloudlibrary',
    summary:
      'Public cloud library serving 240+ public-domain books — accounts, reading progress, reviews and uploads, deployed on a DigitalOcean droplet.',
    category: 'Cloud',
    year: 2026,
    subtag: 'EXPRESS',
    tags: ['Node.js', 'Express', 'PostgreSQL', 'JWT', 'Multer', 'PM2', 'Nginx', 'DigitalOcean'],
    weight: 4,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'vault',
    repoUrl: 'https://github.com/Shazaw/Cloud-Library',
    screenshot: 'cloudlibrary.png',
    description: prose(
      'A full-stack platform for discovering, downloading and sharing public-domain literature, built as a cloud computing project and deployed to a 1 vCPU / 1 GB Ubuntu droplet behind Nginx and PM2.',
      'Readers browse and search the collection, track progress across Saved / Reading / Finished, keep a want-to-read list, upload their own public-domain books and review what they finish. The front end is a vanilla JS SPA with no framework — the whole point was to own every layer.',
    ),
  },
  {
    title: 'BEM UGM Penetration Test',
    slug: 'bemkm-ugm-pentest',
    summary:
      'Security engineer for the BEM KM UGM cabinet site — ran an authorised penetration test against the live platform and reported the findings.',
    category: 'Security Engagement',
    year: 2026,
    subtag: 'PENTEST',
    tags: ['Web Exploitation', 'Reconnaissance', 'Burp Suite', 'OWASP', 'Reporting'],
    weight: 4,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'radar',
    role: 'Security engineer',
    liveUrl: 'https://bemkm.ugm.ac.id/',
    screenshot: 'bemkm-ugm.png',
    description: prose(
      'Authorised security assessment of the BEM KM UGM platform: reconnaissance and surface mapping, then a black-box pass over authentication, authorisation and input handling, with findings written up for the people who had to act on them.',
      'The useful half of this work is never the exploit — it is turning what you found into something a non-security team can prioritise and actually fix.',
    ),
  },
  {
    title: '180DC UGM Website',
    slug: '180dc-ugm-website',
    summary:
      'IT manager for 180 Degrees Consulting UGM — presiding over every initiative on the chapter website and its 300+ applicant open recruitment.',
    category: 'Platform',
    year: 2026,
    subtag: 'IT LEAD',
    tags: ['Web Platform', 'Content Ops', 'Recruitment Systems', 'Analytics', 'Stakeholder Management'],
    weight: 4,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'skyline',
    role: 'IT manager',
    liveUrl: 'https://www.180dcugm.com/',
    screenshot: '180dc-ugm.png',
    description: prose(
      'IT manager for the UGM chapter of 180 Degrees Consulting, presiding over every initiative that runs through the website — the public storefront for a student consultancy that takes on clients who could not otherwise afford one.',
      'Oversaw the open recruitment cycle end to end, carrying 300+ applicants through the site: intake, staged flow and timeline, and the content around it.',
    ),
  },
  {
    title: 'BHOB Market Observation',
    slug: 'bhob-market-observation',
    summary:
      'Web-scraping and digital-market study for an e-commerce client: 553 social posts and 1,411 reviews cleaned, clustered and turned into personas.',
    category: 'Consulting',
    year: 2026,
    subtag: 'PYTHON',
    tags: ['Python', 'Jupyter', 'Pandas', 'scikit-learn', 'K-Means', 'PCA', 'Web Scraping', 'LaTeX'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'lattice',
    repoUrl: 'https://github.com/Shazaw/BHOB-Marketplace-Analysis',
    screenshot: 'bhob-personas.png',
    description: prose(
      'A strategic web-scraping and digital market observation project for Bumi Herbs Oditi Bali, delivered under 180 Degrees Consulting UGM. 553 social posts and 1,411 comments and reviews were collected across Instagram, TikTok, Tokopedia and Shopee, then cleaned into a canonical dataset.',
      'The analysis clusters customers into persona archetypes and maps complaint types, content categories and purchase signals against them. The honest finding was a negative one: marketplace review density is sparse enough that the marketplace channel cannot carry the conclusions on its own.',
    ),
  },
  {
    title: 'CrediWise',
    slug: 'crediwise',
    summary:
      'Two-way credit safety engine for thin-file and gig-economy borrowers in Indonesia. Built for Garuda Hacks 7.0.',
    category: 'Fintech',
    year: 2026,
    subtag: 'FASTAPI',
    tags: ['Python', 'FastAPI', 'SQLAlchemy', 'Alembic', 'Celery', 'PostgreSQL', 'Redis', 'SwiftUI'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'vault',
    repoUrl: 'https://github.com/Shazaw/CrediWise',
    description: doc(
      paragraph(
        'CrediWise turns verified financial records into an explainable view of financial behaviour, repayment capacity, shock resilience and safe borrowing capacity — for users whose income is informal, seasonal or simply invisible to a conventional score.',
      ),
      paragraph(
        'We do not only determine whether a user is creditworthy. We determine whether the credit is worthy of the user.',
      ),
      bullets([
        'Cash-Flow Digital Twin separating personal from business activity.',
        'Deterministic risk and safe-borrowing engines with reason codes — AI can phrase evidence, never calculate a score.',
        'Shock resilience modelling for income drops, delays and weakest-month conditions.',
        'Safe Offer Score ranking simulated loan offers by user suitability rather than commission.',
      ]),
      paragraph(
        'Python and FastAPI backend with a native SwiftUI client; the experimental repayment model is versioned separately and never changes the deterministic outputs.',
      ),
    ),
  },
  {
    title: 'Acme Market Lab',
    slug: 'acme-market-lab',
    summary:
      'Disposable intentionally-vulnerable e-commerce environment for intermediate training, spanning seven network services and a Laravel app.',
    category: 'Security Education',
    year: 2026,
    subtag: 'LARAVEL',
    tags: ['PHP', 'Laravel', 'Blade', 'MySQL', 'Docker', 'Shell', 'BIND9'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'bridge',
    repoUrl: 'https://github.com/Shazaw/Acme-Market-Vulnerable-Lab',
    description: prose(
      'A production-shaped environment students can enumerate, exploit within scope and reset between sessions — HTTP, HTTPS, DNS, FTP, SMTP, SSH and MySQL, plus a Laravel storefront.',
      'Coverage runs from DNS zone transfer and anonymous FTP through avatar-upload RCE, stored XSS, IDOR and a legacy SQL injection login, ending in privilege escalation via a writable cron target and an unsafe SUID binary.',
    ),
  },
  {
    title: 'Penetration Testing Labs',
    slug: 'penetration-testing-labs',
    summary:
      'Four graded vulnerable environments — legacy, easy, medium and hard — written for and used in OmahTI Academy workshops.',
    category: 'Security Education',
    year: 2025,
    subtag: 'PHP',
    tags: ['PHP', 'MySQL', 'Apache', 'Shell', 'Docker'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'lattice',
    repoUrl: 'https://github.com/Shazaw/Penetration-Testing-Vulnerable-Labs',
    description: prose(
      'A structured ladder of vulnerable-by-design applications, inspired by DVWA but graded so a learner has somewhere to go next: a legacy box built around outdated software and service misconfiguration, then easy, medium and hard paths through progressively more modern stacks.',
      'Written for workshops at OmahTI Academy, where the labs had to survive a room full of people attacking them at once.',
    ),
  },
  {
    title: 'CTF Library',
    slug: 'ctf-library',
    summary:
      'Personal CTF hub: write-ups from events played, and the full source for the challenge sets designed and run for others.',
    category: 'Capture the Flag',
    year: 2025,
    subtag: 'CTF',
    tags: ['Docker', 'Node.js', 'HTML', 'Cryptography', 'Forensics', 'OSINT'],
    weight: 2,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'vault',
    repoUrl: 'https://github.com/Shazaw/CTF-Library',
    description: prose(
      'Two things in one repository: solutions and thought process for events played, and the source, setup and answer keys for challenges authored — including the full OmahTI Academy final project covering web exploitation, cryptography, forensics and OSINT.',
      'The authored half is written for people who have never competed before: each challenge teaches exactly one idea and is meant to be solvable in an hour by someone seeing it for the first time.',
    ),
  },
  {
    title: 'E2EE Proto',
    slug: 'e2ee-proto',
    summary: 'Rust prototype of an end-to-end encrypted messaging layer, exploring the Signal-style session handshake.',
    category: 'Cryptography',
    year: 2025,
    subtag: 'RUST',
    tags: ['Rust', 'Cryptography', 'Docker'],
    weight: 2,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'vault',
    repoUrl: 'https://github.com/Shazaw/E2EE-Proto',
    description: prose(
      'A small Rust prototype for an end-to-end encrypted messaging layer — the session handshake and ratcheting state written from the protocol description rather than pulled from a library, because that is the only way to find out which parts you did not actually understand.',
    ),
  },
  {
    title: 'OmahTI Academy Cybersecurity',
    slug: 'omahti-academy-cybersecurity',
    summary: 'Hands-on teaching material for the OmahTI Academy security track — forensics, steganography and file carving exercises.',
    category: 'Security Education',
    year: 2026,
    subtag: 'PYTHON',
    tags: ['Python', 'Forensics', 'Steganography', 'Hex Editing', 'Metadata'],
    weight: 2,
    featured: false,
    mosaicSpan: 'auto',
    stripArtwork: 'radar',
    repoUrl: 'https://github.com/Shazaw/OmahTIAcademy_Hands_On_Practice_Cysec',
    description: prose(
      'Practice material for the security track at OmahTI Academy: file carving, hex-editor work, metadata extraction and LSB steganography, each built around an artefact students take apart themselves rather than a walkthrough they follow.',
    ),
  },
] as const
