import { bullets, doc, paragraph, prose } from './richtext'

/**
 * SEED DATA — placeholder records. Grounded in the references carried by the
 * approved prototype, but every one of these should be verified and rewritten
 * at /admin before the site is published.
 */

export const experiences = [
  {
    title: 'Consultant',
    slug: 'consultant-180dc-ugm',
    organization: '180 Degrees Consulting UGM',
    location: 'Yogyakarta, ID',
    startDate: '2025-09-01',
    endDate: null,
    current: true,
    employmentType: 'volunteer',
    summary: 'Digital-infrastructure and UX engagements for small businesses and NGOs.',
    subtag: 'UX',
    tags: ['CONSULTING', 'UX', 'STRATEGY'],
    weight: 5,
    featured: true,
    featuredOrder: 1,
    mosaicSpan: '4',
    highlights: [
      'Ran a live UX audit and digital roadmap for an e-commerce client.',
      'Built a reusable deck-generation pipeline now used across engagements.',
      'Translated technical findings into decisions non-technical clients could act on.',
    ],
    description: prose(
      'Client-facing consulting on digital infrastructure: auditing what exists, mapping what it costs to keep, and staging what to build next.',
    ),
    links: [],
  },
  {
    title: 'Product Manager',
    slug: 'product-manager-efn-ugm',
    organization: 'EFN UGM',
    location: 'Yogyakarta, ID',
    startDate: '2025-02-01',
    endDate: '2026-06-01',
    current: false,
    employmentType: 'part-time',
    summary: 'Product lead on OptiWealth, a predictive personal-finance platform, in a five-person founding team.',
    subtag: 'PM',
    tags: ['PRODUCT', 'FINTECH', 'ML'],
    weight: 4,
    featured: true,
    featuredOrder: 2,
    mosaicSpan: 'auto',
    highlights: [
      'Owned scope and roadmap across a five-person founding team.',
      'Cut the first release scope roughly in half to reach a testable build.',
    ],
    description: prose(
      'Product management on a small founding team, which mostly meant deciding what not to build and defending that decision weekly.',
    ),
    links: [],
  },
  {
    title: 'Undergraduate Researcher',
    slug: 'undergraduate-researcher-ugm',
    organization: 'Universitas Gadjah Mada',
    location: 'Yogyakarta, ID',
    startDate: '2026-01-01',
    endDate: null,
    current: true,
    employmentType: 'research',
    summary: 'Research into agentic LLM workflows applied to penetration testing.',
    subtag: 'RESEARCH',
    tags: ['RESEARCH', 'LLM', 'SECURITY'],
    weight: 4,
    featured: true,
    featuredOrder: 3,
    mosaicSpan: 'auto',
    highlights: [
      'Built the evaluation harness used to score agent runs against known targets.',
      'Documented failure modes where agents assert findings they cannot support.',
    ],
    description: prose(
      'Where automated agents genuinely help a penetration test, where they quietly hallucinate, and how to tell the two apart from the transcript alone.',
    ),
    links: [],
  },
  {
    title: 'Encryption Engineering (independent)',
    slug: 'encryption-engineering-independent',
    organization: 'Independent',
    location: 'Remote',
    startDate: '2025-06-01',
    endDate: null,
    current: true,
    employmentType: 'freelance',
    summary: 'Applied cryptography work: protocol implementation, review and benchmarking.',
    subtag: 'CRYPTO',
    tags: ['CRYPTO', 'RUST', 'PROTOCOLS'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    highlights: ['Implemented and benchmarked a Signal-Protocol-derived messaging layer.'],
    description: prose(
      'Independent applied-cryptography work, primarily protocol implementation and the review that has to follow it.',
    ),
    links: [],
  },
] as const

export const organizations = [
  {
    title: '180 Degrees Consulting UGM',
    slug: '180dc-ugm',
    role: 'Consultant',
    startDate: '2025-09-01',
    endDate: null,
    current: true,
    summary: 'Student-run consultancy serving NGOs and small businesses.',
    subtag: 'CONSULTING',
    tags: ['CONSULTING', 'STRATEGY'],
    weight: 5,
    featured: true,
    featuredOrder: 1,
    mosaicSpan: '4',
    highlights: ['Delivered engagements across UX, digital infrastructure and go-to-market.'],
    description: prose(
      'The local chapter of a student-run consultancy that takes on clients who could not otherwise afford consulting.',
    ),
    links: [],
  },
  {
    title: 'EFN UGM',
    slug: 'efn-ugm',
    role: 'Product Manager',
    startDate: '2025-02-01',
    endDate: '2026-06-01',
    current: false,
    summary: 'Entrepreneurship and financial network building student ventures.',
    subtag: 'PRODUCT',
    tags: ['ENTREPRENEURSHIP', 'PRODUCT'],
    weight: 4,
    featured: true,
    featuredOrder: 2,
    mosaicSpan: 'auto',
    highlights: ['Founding product manager on OptiWealth.'],
    description: prose('A student network that incubates ventures rather than running events about them.'),
    links: [],
  },
  {
    title: 'UGM Cybersecurity Community',
    slug: 'ugm-cybersecurity-community',
    role: 'CTF Player & Author',
    startDate: '2024-09-01',
    endDate: null,
    current: true,
    summary: 'Campus security community — competition play, internal CTFs and training material.',
    subtag: 'CTF',
    tags: ['CTF', 'SECURITY', 'TEACHING'],
    weight: 4,
    featured: true,
    featuredOrder: 3,
    mosaicSpan: 'auto',
    highlights: [
      'Play competitions across crypto, web and forensics.',
      'Author challenges for internal events and write the accompanying material.',
    ],
    description: prose(
      'Playing competitions is half of it; the other half is writing challenges that teach something to the people who solve them.',
    ),
    links: [],
  },
] as const

export const awards = [
  {
    title: 'UI Innovation War 2026',
    slug: 'ui-innovation-war-2026',
    issuer: 'Universitas Indonesia',
    placement: 'Case Winner',
    date: '2026-04-01',
    scope: 'national',
    summary: 'Winning case submission on a community-solar pilot: risk register, roadmap and replication triggers.',
    subtag: 'STRATEGY',
    tags: ['CASE', 'STRATEGY', 'ENERGY'],
    weight: 5,
    featured: true,
    featuredOrder: 1,
    mosaicSpan: '4',
    description: prose(
      'A national case competition. The submission argued that the pilot should be judged on whether it produced replication conditions, not on whether it produced power.',
    ),
    links: [],
  },
  {
    title: 'National CTF Finals',
    slug: 'national-ctf-finals',
    issuer: 'Cyber Jawara',
    placement: 'Finalist',
    date: '2025-11-01',
    scope: 'national',
    summary: 'Reached the national finals in a jeopardy-format capture-the-flag competition.',
    subtag: 'CTF',
    tags: ['CTF', 'SECURITY'],
    weight: 4,
    featured: true,
    featuredOrder: 2,
    mosaicSpan: 'auto',
    description: prose('Qualified through the online round and played the on-site final.'),
    links: [],
  },
  {
    title: 'Gemastik Cybersecurity Division',
    slug: 'gemastik-cybersecurity',
    issuer: 'Kemdikbud',
    placement: 'Semifinalist',
    date: '2025-09-01',
    scope: 'national',
    summary: 'National student ICT competition — security division.',
    subtag: 'SECURITY',
    tags: ['CTF', 'COMPETITION'],
    weight: 3,
    featured: true,
    featuredOrder: 3,
    mosaicSpan: 'auto',
    description: prose('The national student ICT competition, security division.'),
    links: [],
  },
  {
    title: "Dean's List",
    slug: 'deans-list',
    issuer: 'Universitas Gadjah Mada',
    placement: null,
    date: '2025-07-01',
    scope: 'university',
    summary: 'Faculty recognition for academic standing.',
    subtag: 'ACADEMIC',
    tags: ['ACADEMIC'],
    weight: 2,
    featured: false,
    mosaicSpan: 'auto',
    description: prose('Faculty recognition for academic standing.'),
    links: [],
  },
] as const

export const profileSeed = {
  name: 'M. Ahsan Zaki Wiryawan',
  initials: 'AZW',
  heroLineOne: 'M. AHSAN ZAKI',
  heroLineTwo: 'WIRYAWAN',
  tagline:
    'Computer science undergraduate at UGM. Cybersecurity concentration — CTF player, encryption engineer, and occasional consultant.',
  role: 'CS undergraduate · cybersecurity',
  aboutIntro:
    'I build things that have to hold up when someone is actively trying to break them — encryption layers, red-team tooling, and the occasional consulting engagement where the real problem turns out to be the infrastructure nobody documented.',
  email: 'ahsan.wiryawan@gmail.com',
  location: 'Yogyakarta, ID',
  coordinates: "07°46′S 110°22′E · UGM",
  about: doc(
    paragraph(
      'I am a computer science undergraduate at Universitas Gadjah Mada, concentrating in cybersecurity. Most of my time goes to three things: applied cryptography, capture-the-flag competitions on both sides of the board, and consulting engagements where the deliverable is a decision rather than a codebase.',
    ),
    paragraph(
      'The through-line is the same in all three. A system is only as good as its worst assumption, and most of the work is finding out which assumption that is before somebody else does.',
    ),
    bullets([
      'Encryption engineering — protocol implementation, review, benchmarking.',
      'Offensive security — CTF play, red-team tooling, agentic testing research.',
      'Consulting — UX audits, cloud migration architecture, digital roadmaps.',
    ]),
    paragraph(
      'This site is a survey document rather than a gallery. Every section is the same data seen two ways: a spatial cluster you can orbit, and a flat grid you can read. The grid is the product; the cluster is the fireworks.',
    ),
  ),
  focusAreas: [
    {
      title: 'Applied cryptography',
      body: 'Protocol implementation and review — X3DH, Double Ratchet, AEAD constructions, and the state machines that hold them together.',
      tag: 'CRYPTO',
    },
    {
      title: 'Offensive security',
      body: 'Capture the flag as a player and an author, plus research into how far agentic tooling can carry a penetration test.',
      tag: 'REDTEAM',
    },
    {
      title: 'Systems consulting',
      body: 'UX audits, cloud migration architecture and cost modelling for organisations without a technical function of their own.',
      tag: 'ADVISORY',
    },
  ],
  skills: [
    { group: 'Languages', items: ['Rust', 'TypeScript', 'Python', 'C', 'Go', 'SQL'] },
    { group: 'Security', items: ['Applied cryptography', 'Web exploitation', 'Forensics', 'Reverse engineering', 'Threat modelling'] },
    { group: 'Platform', items: ['Next.js', 'PostgreSQL', 'AWS', 'Docker', 'Linux'] },
    { group: 'Practice', items: ['Product management', 'UX audit', 'Technical writing', 'Cost modelling'] },
  ],
  education: [
    {
      institution: 'Universitas Gadjah Mada',
      program: 'BSc Computer Science — cybersecurity concentration',
      period: '2023 — present',
      detail: 'Yogyakarta',
    },
  ],
  socials: [
    { label: 'GitHub', url: 'https://github.com/' },
    { label: 'LinkedIn', url: 'https://www.linkedin.com/' },
  ],
  siteTitle: 'M. Ahsan Zaki Wiryawan',
  siteDescription:
    'Portfolio of M. Ahsan Zaki Wiryawan — computer science undergraduate at UGM, cybersecurity concentration. Encryption engineering, CTF, and systems consulting.',
} as const
