import { bullets, doc, paragraph, prose } from './richtext'

/**
 * SEED DATA — placeholder records. Grounded in the references carried by the
 * approved prototype, but every one of these should be verified and rewritten
 * at /admin before the site is published.
 */

export const experiences = [
  {
    title: 'Lead Security Engineer',
    slug: 'lead-security-engineer-sanct-social',
    organization: 'Sanct Social',
    location: 'Remote',
    startDate: '2025-09-01',
    endDate: null,
    current: true,
    employmentType: 'part-time',
    summary:
      'Own the end-to-end encryption layer and the security backend, and lead two engineers across the AI features and encrypted chat.',
    subtag: 'CRYPTO',
    tags: ['End-to-End Encryption', 'KVAC', 'Applied Cryptography', 'Security Backend', 'Team Leadership'],
    weight: 5,
    featured: true,
    featuredOrder: 1,
    mosaicSpan: '4',
    highlights: [
      'Own the end-to-end encryption protecting user-to-user chat.',
      'Added keyed-verification anonymous credentials so a member can prove they belong to a group without exposing who else is in it.',
      'Built and maintain the security backend the rest of the product authenticates against.',
      'Lead two security engineers across the AI features and the encrypted chat path.',
    ],
    description: prose(
      'Sanct Social treats its privacy guarantees as a feature rather than a footnote, which means the cryptography is not a layer bolted on at the end. It decides what the product can and cannot offer.',
      'My remit is the encryption layer and the security backend beneath it: the end-to-end path carrying user-to-user chat, and a keyed-verification anonymous credential scheme that lets a member prove group membership without disclosing who else belongs. I lead two security engineers, split between the AI features and the encrypted chat path.',
    ),
    links: [],
  },
  {
    title: 'Project Analyst',
    slug: 'project-analyst-180dc-ugm',
    organization: '180 Degrees Consulting UGM',
    location: 'Yogyakarta, ID',
    startDate: '2026-02-01',
    endDate: null,
    current: true,
    employmentType: 'part-time',
    summary:
      'Client consulting for an e-commerce business: competitor-intelligence tooling, search visibility, analytics and a UX pass.',
    subtag: 'STRATEGY',
    tags: ['Consulting', 'Web Scraping', 'Python', 'SEO', 'GA4 Analytics', 'UI/UX'],
    weight: 5,
    featured: true,
    featuredOrder: 2,
    mosaicSpan: 'auto',
    highlights: [
      'Built a web scraper turning scattered competitor pricing and positioning into a dataset the team could compare against.',
      'Rebuilt the storefront’s search visibility through on-page SEO.',
      'Instrumented GA4 so the funnel could be measured instead of guessed at.',
      'Redesigned the interface around what that instrumentation actually showed.',
    ],
    description: prose(
      'Client work under 180 Degrees Consulting UGM, the student-run consultancy that takes on organisations who could not otherwise afford the help. The commercial specifics stay with the client; what I can describe is what I built.',
      'Competitor intelligence was the first gap, since nobody had a view of what the rest of the category charged or claimed, so I wrote a scraper to turn that into something comparable. The rest was making the storefront legible to search engines and to people: on-page SEO, GA4 instrumentation so the funnel could be measured, and a UX pass driven by what the numbers showed rather than by taste.',
    ),
    links: [],
  },
  {
    title: 'Security Engineer, Research & Development',
    slug: 'security-engineer-bem-km-ugm',
    organization: 'BEM KM UGM',
    location: 'Yogyakarta, ID',
    startDate: '2025-09-01',
    endDate: '2026-02-01',
    current: false,
    employmentType: 'freelance',
    summary:
      'Ran an authorised vulnerability assessment of the student executive board’s platform and wrote the findings up for a team with no security function.',
    subtag: 'PENTEST',
    tags: ['Penetration Testing', 'Vulnerability Assessment', 'Web Exploitation', 'OWASP', 'Reporting'],
    weight: 4,
    featured: true,
    featuredOrder: 3,
    mosaicSpan: 'auto',
    highlights: [
      'Assessed the live platform under an authorised scope.',
      'Reproduced every issue by hand rather than forwarding scanner output.',
      'Wrote the report for the people who had to fix it, not for other security engineers.',
    ],
    description: prose(
      'An authorised security assessment of the BEM KM UGM platform under the research and development department: surface mapping first, then a pass across authentication, authorisation and input handling, reproducing each issue rather than trusting a tool to be right about it.',
      'The report was the deliverable that mattered. A finding a non-security team cannot act on is not really a finding, so each one landed with its impact in plain language and a place in the queue relative to everything else they had to do.',
    ),
    links: [],
  },
  {
    title: 'Teaching Assistant, Penetration Testing',
    slug: 'teaching-assistant-omahti-academy-2026',
    organization: 'OmahTI Academy',
    location: 'Yogyakarta, ID',
    startDate: '2026-03-01',
    endDate: null,
    current: true,
    employmentType: 'assistantship',
    summary:
      'Second cohort of the penetration-testing track. I designed the curriculum and its labs, and mentor students through them alongside a practitioner from industry.',
    subtag: 'TEACHING',
    tags: ['Curriculum Design', 'Lab Engineering', 'Penetration Testing', 'Mentoring'],
    weight: 4,
    featured: false,
    mosaicSpan: 'auto',
    highlights: [
      'Designed the curriculum for the penetration-testing track.',
      'Built both the teaching labs and the separate labs students are assessed against.',
      'Co-taught with a practitioner working in the field, and mentored students through the material.',
    ],
    description: prose(
      'The security track of OmahTI Academy, back for a second cohort. I design the curriculum and build the environments it runs on, keeping teaching labs and assessment labs deliberately separate, because demonstrating a technique and testing whether it landed are not the same exercise.',
      'Teaching alongside someone doing the work professionally keeps the material honest about the job rather than the syllabus. The rest is mentoring: sitting with students while they are stuck, which is where most of the learning actually happens.',
    ),
    links: [],
  },
  {
    title: 'Teaching Assistant & Mentor, Cybersecurity',
    slug: 'teaching-assistant-omahti-academy-2025',
    organization: 'OmahTI Academy',
    location: 'Yogyakarta, ID',
    startDate: '2025-03-01',
    endDate: '2025-07-01',
    current: false,
    employmentType: 'assistantship',
    summary:
      'Built the academy’s first penetration-testing curriculum and the vulnerable labs it runs on, and mentored the fundamentals cohort through them.',
    subtag: 'TEACHING',
    tags: ['Curriculum Design', 'Lab Engineering', 'Penetration Testing', 'Mentoring'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    highlights: [
      'Wrote the first version of the penetration-testing curriculum.',
      'Built the vulnerable labs it was taught on, several later published as an open repository.',
      'Mentored the fundamental cybersecurity cohort in parallel with the pentesting track.',
    ],
    description: prose(
      'The first run of the security track, where everything had to exist before it could be taught: the curriculum, the vulnerable environments to teach it on, and the graded labs to check any of it had landed. Several of those labs are public now as Penetration Testing Vulnerable Labs.',
      'Running a workshop where the entire room attacks the same box at once teaches you as much about lab engineering as it does about teaching.',
    ),
    links: [],
  },
  {
    title: 'Problem Setter & Person in Charge',
    slug: 'problem-setter-joints-inspire-ctf',
    organization: 'JOINTS × Inspire',
    location: 'Yogyakarta, ID',
    startDate: '2026-03-01',
    endDate: '2026-06-01',
    current: false,
    employmentType: 'volunteer',
    summary:
      'Ran the JOINTS × Inspire capture-the-flag competition end to end and authored part of the challenge set.',
    subtag: 'CTF',
    tags: ['CTF', 'Challenge Design', 'Event Operations', 'Cryptography', 'Web Exploitation'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    highlights: [
      'Person in charge of the competition: format, infrastructure, timeline and the room on the day.',
      'Authored part of the challenge set.',
      'Tuned the difficulty curve so newer teams could get on the board and strong ones still had somewhere to go.',
    ],
    description: prose(
      'Person in charge of the JOINTS × Inspire CTF, from the format and infrastructure through to running the event itself, plus a share of the challenges.',
      'Setting problems for a mixed field is its own constraint. A challenge nobody solves teaches nobody anything; one everybody clears in five minutes is filler. Almost all the work lives in the curve between those two.',
    ),
    links: [],
  },
] as const

export const organizations = [
  {
    title: 'OmahTI UGM',
    slug: 'omahti-ugm',
    role: 'Head of Cybersecurity Division',
    startDate: '2024-12-01',
    endDate: null,
    current: true,
    summary:
      'UGM’s information technology student organisation. Head of the cybersecurity division, after two years through its competition and security tracks.',
    subtag: 'SECURITY',
    tags: ['Cybersecurity', 'CTF', 'Competition Research', 'Mentoring'],
    weight: 5,
    featured: true,
    featuredOrder: 1,
    mosaicSpan: '4',
    highlights: [
      'Head of Cybersecurity Division, Jan 2026 to present.',
      'Junior Staff, Research and Competition, Jan 2025 to Jan 2026.',
      'Junior Staff, Cybersecurity Division, Dec 2024 to Jan 2026.',
    ],
    description: prose(
      'Organisasi Mahasiswa Ahli Teknologi Informasi, UGM’s IT student organisation. I came in through the cybersecurity division on weekly CTF training, specialising in web exploitation, digital forensics and binary exploitation, and competing across national and international events with consistent top 30 finishes.',
      'In parallel I ran research and competition: reaching the Faculty of Mathematics and Natural Sciences ahead of GELATIK 2025, mobilising more than twenty prospective teams, then designing the preparatory programme of materials, past paper analysis and competition insight that got them ready. Since January 2026 I have led the cybersecurity division.',
    ),
    links: [],
  },
  {
    title: 'KOMATIK UGM',
    slug: 'komatik-ugm',
    role: 'Head of Cybersecurity Division (ASGama)',
    startDate: '2024-11-01',
    endDate: null,
    current: true,
    summary:
      'UGM’s ICT student community. Head of the ASGama cybersecurity division, having come up through its training and competition ranks.',
    subtag: 'CTF',
    tags: ['Cybersecurity', 'CTF', 'Forensics', 'Reverse Engineering', 'Cryptography'],
    weight: 4,
    featured: true,
    featuredOrder: 2,
    mosaicSpan: 'auto',
    highlights: [
      'Head of Cybersecurity Division (ASGama), Jan 2026 to present.',
      'Junior Staff, Cybersecurity Division (ASGama), Nov 2024 to Jan 2026.',
    ],
    description: prose(
      'Komunitas Mahasiswa TIK, UGM’s ICT student community. I joined the ASGama cybersecurity division as junior staff, contributing to weekly training and teaching the core CTF categories of forensics, web exploitation, reverse engineering and cryptography to members building the same skills.',
      'The competition side ran alongside it: a Top 4 placement in Liga Komatik as part of the core team, and the intensive preparation for GELATIK. I have led the division since January 2026.',
    ),
    links: [],
  },
  {
    title: '180 Degrees Consulting UGM',
    slug: '180dc-ugm',
    role: 'IT Manager',
    startDate: '2026-02-01',
    endDate: null,
    current: true,
    summary:
      'The UGM chapter of the world’s largest student-led consultancy for non-profits and social enterprises. IT manager for the chapter platform.',
    subtag: 'IT LEAD',
    tags: ['Web Platform', 'Content Ops', 'Recruitment Systems', 'Analytics'],
    weight: 4,
    featured: true,
    featuredOrder: 3,
    mosaicSpan: 'auto',
    highlights: [
      'IT Manager, Jul 2026 to present.',
      'Project Analyst, Feb 2026 to present.',
      'Oversaw an open recruitment cycle carrying 300+ applicants through the chapter site.',
    ],
    description: prose(
      'The UGM chapter of 180 Degrees Consulting, which takes on clients who could not otherwise afford consulting. I joined as a project analyst on client engagements and took on the IT manager role in July 2026.',
      'As IT manager I preside over every initiative that runs through the chapter website: the public storefront for the consultancy, the content around it, and the open recruitment cycle that carried more than three hundred applicants through intake, staged flow and timeline.',
    ),
    links: [],
  },
  {
    title: 'BEM KM UGM',
    slug: 'bem-km-ugm',
    role: 'Security Engineer, Research & Development',
    startDate: '2025-09-01',
    endDate: '2026-02-01',
    current: false,
    summary:
      'The student executive board of UGM. Security engineer within the research and development department for the 2025 cabinet.',
    subtag: 'SECURITY',
    tags: ['Cybersecurity', 'Penetration Testing', 'Research & Development'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    highlights: ['Security Engineer, Department of Research and Development, Sep 2025 to Feb 2026.'],
    description: prose(
      'Badan Eksekutif Mahasiswa Keluarga Mahasiswa UGM, the university’s student executive board. I sat in the research and development department as its security engineer for the 2025 cabinet, where the assessment of the board’s own platform came out of the role.',
    ),
    links: [],
  },
  {
    title: 'AIESEC in UGM',
    slug: 'aiesec-in-ugm',
    role: 'OC Vice President, Program & Partnership',
    startDate: '2024-10-01',
    endDate: '2026-02-01',
    current: false,
    summary:
      'Global youth leadership organisation. Ran quality control for outgoing volunteers, then vice-presided over programme and partnership at the alumni gathering.',
    subtag: 'OPERATIONS',
    tags: ['Programme Operations', 'CRM', 'Customer Experience', 'Partnerships'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    highlights: [
      'OC Vice President, Program & Partnership, Alumni Gathering, Sep 2025 to Feb 2026.',
      'Assessor, Join AIESEC in UGM 2025, Jul 2025.',
      'Quality Control & Customer Experience Staff, Outgoing Global Volunteer, Jan 2025 to Feb 2026.',
      'Intern, Outgoing Global Volunteer, Oct 2024 to Jan 2025.',
    ],
    description: prose(
      'AIESEC’s local committee at UGM. I started as an intern on outgoing global volunteer, learning the exchange workflow end to end through project matching, participant support and quality assurance, then took it on as quality control and customer experience staff.',
      'That meant being the first point of contact for prospective exchange participants, owning their outbound journey against the quality standard, and refining an automated communication workflow that carried more than a thousand prospects through it. Later I served as organising committee vice president for programme and partnership at the alumni gathering, and as an assessor for the 2025 intake.',
    ),
    links: [],
  },
  {
    title: 'UGM MUN Community',
    slug: 'ugm-mun-community',
    role: 'Member',
    startDate: '2025-09-01',
    endDate: '2026-02-01',
    current: false,
    summary: 'Member of the UGM Model United Nations community.',
    subtag: null,
    tags: [],
    weight: 2,
    featured: false,
    mosaicSpan: 'auto',
    highlights: [],
    description: null,
    links: [],
  },
] as const

export const awards = [
  {
    title: 'PsychCTF 2026',
    slug: 'psychctf-2026-first-place',
    issuer: 'SAIC, IIT Mandi',
    placement: '1ST PLACE',
    date: '2026-03-01',
    scope: 'international',
    summary: 'First place at PsychCTF 2026, hosted by the Student Academic Improvement Cell at IIT Mandi.',
    subtag: 'CTF',
    tags: ['CTF', 'International'],
    weight: 5,
    featured: true,
    featuredOrder: 1,
    mosaicSpan: '4',
    description: null,
    links: [],
  },
  {
    title: 'ApoorvCTF 2026',
    slug: 'apoorvctf-2026-second-place',
    issuer: 'ApoorvCTF, IIIT Kottayam',
    placement: '2ND PLACE',
    date: '2026-03-01',
    scope: 'international',
    summary: 'Runner-up at ApoorvCTF 2026, hosted by IIIT Kottayam.',
    subtag: 'CTF',
    tags: ['CTF', 'International'],
    weight: 5,
    featured: true,
    featuredOrder: 2,
    mosaicSpan: 'auto',
    description: null,
    links: [],
  },
  {
    title: 'Garuda Hacks 7.0',
    slug: 'garuda-hacks-7-top-15',
    issuer: 'UMN Garuda Hacks',
    placement: 'TOP 15%',
    date: '2026-07-01',
    scope: 'national',
    summary: 'CrediWise placed in the top 15% of project submissions at Garuda Hacks 7.0.',
    subtag: 'HACKATHON',
    tags: ['Hackathon', 'Fintech'],
    weight: 4,
    featured: true,
    featuredOrder: 3,
    mosaicSpan: 'auto',
    description: null,
    links: [],
  },
  {
    title: 'FindIT 2026 CTF',
    slug: 'findit-2026-ctf-finalist',
    issuer: 'FindIT UGM',
    placement: 'FINALIST',
    date: '2026-05-01',
    scope: 'national',
    summary: 'Reached the finals of the FindIT 2026 capture-the-flag competition.',
    subtag: 'CTF',
    tags: ['CTF', 'National'],
    weight: 4,
    featured: false,
    mosaicSpan: 'auto',
    description: null,
    links: [],
  },
  {
    title: 'DCSE Summer Course',
    slug: 'dcse-summer-course-honorable-mention',
    issuer: 'Universitas Gadjah Mada',
    placement: 'HONORABLE MENTION',
    date: '2025-08-01',
    scope: 'university',
    summary: 'Awarded for AutoSIEM, the ML and generative-AI SIEM prototype built during the UGM DCSE Summer Course 2025.',
    subtag: 'PROJECT',
    tags: ['Machine Learning', 'SIEM'],
    weight: 4,
    featured: false,
    mosaicSpan: 'auto',
    description: null,
    links: [],
  },
  {
    title: 'Techcomfest CTF 2025',
    slug: 'techcomfest-ctf-2025-finalist',
    issuer: 'Techcomfest PCC',
    placement: 'FINALIST',
    date: '2026-01-01',
    scope: 'national',
    summary: 'Reached the finals of the Techcomfest 2025 capture-the-flag competition.',
    subtag: 'CTF',
    tags: ['CTF', 'National'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    description: null,
    links: [],
  },
  {
    title: 'Healthkathon CTF 2025',
    slug: 'healthkathon-ctf-2025-finalist',
    issuer: 'BPJS Kesehatan',
    placement: 'FINALIST',
    date: '2025-11-01',
    scope: 'national',
    summary: 'Reached the finals of the Healthkathon 2025 capture-the-flag competition, run by BPJS Kesehatan.',
    subtag: 'CTF',
    tags: ['CTF', 'National'],
    weight: 3,
    featured: false,
    mosaicSpan: 'auto',
    description: null,
    links: [],
  },
] as const

export const profileSeed = {
  name: 'M. Ahsan Zaki Wiryawan',
  initials: 'AZW',
  heroLineOne: 'M. AHSAN ZAKI',
  heroLineTwo: 'WIRYAWAN',
  heroAccentWord: 'AHSAN',
  tagline:
    'Computer science undergraduate at UGM, cybersecurity concentration. CTF player, encryption engineer, and occasional consultant.',
  role: 'CS undergraduate · cybersecurity',
  aboutIntro:
    'I build things that have to hold up when someone is actively trying to break them: encryption layers, red-team tooling, and the occasional consulting engagement where the real problem turns out to be the infrastructure nobody documented.',
  email: 'ahsan.wiryawan@gmail.com',
  location: 'Yogyakarta, ID',
  coordinates: "07°46′S 110°22′E · UGM",
  about: doc(
    paragraph(
      'Computer science undergraduate at Universitas Gadjah Mada, concentrating in cybersecurity. Most of my time goes to three things: applied cryptography, capture-the-flag on both sides of the board, and consulting engagements where the deliverable is a decision rather than a codebase.',
    ),
    paragraph(
      'Right now that means leading the security engineering at Sanct Social, covering the end-to-end encryption layer and the credential scheme behind its group privacy, while heading the cybersecurity divisions at OmahTI and KOMATIK and designing the penetration-testing curriculum that OmahTI Academy teaches from.',
    ),
    paragraph(
      'The through-line is the same everywhere. A system is only as good as its worst assumption, and most of the work is finding out which assumption that is before somebody else does.',
    ),
  ),
  focusAreas: [
    {
      title: 'Applied cryptography',
      body: 'Protocol implementation and review: X3DH, Double Ratchet, AEAD constructions, and the state machines that hold them together.',
      tag: 'CRYPTO',
    },
    {
      title: 'Offensive security',
      body: 'Capture the flag as a player and an author, plus research into how far agentic tooling can carry a penetration test.',
      tag: 'REDTEAM',
    },
    {
      title: 'Systems consulting',
      body: 'UX audits, cloud migration architecture and cost modelling for organisations without a technical function of their own.',
      tag: 'ADVISORY',
    },
  ],
  skills: [
    { group: 'Languages', items: ['Rust', 'TypeScript', 'Python', 'C', 'Go', 'SQL'] },
    { group: 'Security', items: ['Applied cryptography', 'Web exploitation', 'Forensics', 'Reverse engineering', 'Threat modelling'] },
    { group: 'Platform', items: ['Next.js', 'PostgreSQL', 'AWS', 'Docker', 'Linux'] },
    { group: 'Practice', items: ['Product management', 'UX audit', 'Technical writing', 'Cost modelling'] },
  ],
  education: [
    {
      institution: 'Universitas Gadjah Mada',
      program: 'BSc Computer Science',
      period: '2023 to present',
      detail: 'Yogyakarta',
    },
    {
      institution: 'Jeonbuk National University',
      program: 'Computer Science and Artificial Intelligence',
      period: 'Sep 2026 to Dec 2026',
      detail: 'Exchange student, Jeonju',
    },
  ],
  socials: [
    { label: 'GitHub', url: 'https://github.com/' },
    { label: 'LinkedIn', url: 'https://www.linkedin.com/' },
  ],
  siteTitle: 'M. Ahsan Zaki Wiryawan',
  siteDescription:
    'Portfolio of M. Ahsan Zaki Wiryawan, computer science undergraduate at UGM with a cybersecurity concentration. Encryption engineering, CTF, and systems consulting.',
} as const
