/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    experiences: Experience;
    organizations: Organization;
    awards: Award;
    'ctf-competitions': CtfCompetition;
    'ctf-challenges': CtfChallenge;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    'ctf-competitions': CtfCompetitionsSelect<false> | CtfCompetitionsSelect<true>;
    'ctf-challenges': CtfChallengesSelect<false> | CtfChallengesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    profile: Profile;
  };
  globalsSelect: {
    profile: ProfileSelect<false> | ProfileSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Builds and research. Weight decides tower height in the chamber.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Leave blank to derive from the title.
   */
  slug?: string | null;
  /**
   * One line. Shown in mosaic cells and homepage strips.
   */
  summary: string;
  /**
   * e.g. ENCRYPTION, PLATFORM, RESEARCH.
   */
  category: string;
  /**
   * Optional. When it shipped, to the month — shown as e.g. AUG 2026.
   */
  date?: string | null;
  /**
   * Derived from the date when one is set.
   */
  year: number;
  /**
   * Short mono tag shown beside the title. Defaults to the first tag.
   */
  subtag?: string | null;
  /**
   * The full stack, in the order you want it read. Shown complete on the homepage card and in the expanded mosaic cell.
   */
  tags?: string[] | null;
  /**
   * Long form. Loaded lazily when the popup card opens.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Drives the GITHUB button.
   */
  repoUrl?: string | null;
  /**
   * Drives the LIVE button.
   */
  liveUrl?: string | null;
  /**
   * Your part in it, when it needs saying — e.g. Security engineer, IT manager.
   */
  role?: string | null;
  /**
   * Buttons rendered inside the popup card.
   */
  links?:
    | {
        /**
         * e.g. GITHUB, WRITE-UP, LIVE
         */
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. A real screenshot of the running project — shown on the homepage card and in the expanded mosaic cell. Without one, the generated wireframe artwork is used instead.
   */
  screenshot?: (number | null) | Media;
  /**
   * Wireframe motif drawn in the homepage strip cell.
   */
  stripArtwork?: ('auto' | 'skyline' | 'tower' | 'bridge' | 'lattice' | 'radar' | 'vault') | null;
  /**
   * 1–5. Drives tower height in the chamber and ordering everywhere.
   */
  weight: number;
  /**
   * Width of this item inside the CARDS mosaic.
   */
  mosaicSpan?: ('auto' | '2' | '3' | '4') | null;
  /**
   * Show in this section's homepage card strip.
   */
  featured?: boolean | null;
  /**
   * Order inside the homepage strip. Lower first.
   */
  featuredOrder?: number | null;
  /**
   * Unpublished items are hidden from the public site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Roles held. `title` is the role, e.g. Security Engineering Intern.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  /**
   * Leave blank to derive from the title.
   */
  slug?: string | null;
  organization: string;
  location?: string | null;
  startDate: string;
  endDate?: string | null;
  current?: boolean | null;
  employmentType?: ('internship' | 'part-time' | 'freelance' | 'research' | 'assistantship' | 'volunteer') | null;
  /**
   * One line. Shown in mosaic cells and homepage strips.
   */
  summary: string;
  /**
   * Short mono tag shown beside the title. Defaults to the first tag.
   */
  subtag?: string | null;
  /**
   * Short uppercase keywords, e.g. RUST, CRYPTO, X3DH.
   */
  tags?: string[] | null;
  /**
   * Bullet outcomes shown in the popup card.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Buttons rendered inside the popup card.
   */
  links?:
    | {
        /**
         * e.g. GITHUB, WRITE-UP, LIVE
         */
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  /**
   * Derived from the dates above.
   */
  year?: number | null;
  /**
   * 1–5. Drives tower height in the chamber and ordering everywhere.
   */
  weight: number;
  /**
   * Width of this item inside the CARDS mosaic.
   */
  mosaicSpan?: ('auto' | '2' | '3' | '4') | null;
  /**
   * Show in this section's homepage card strip.
   */
  featured?: boolean | null;
  featuredOrder?: number | null;
  /**
   * Unpublished items are hidden from the public site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Societies, chapters and student bodies. `title` is the organization.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  title: string;
  /**
   * Leave blank to derive from the title.
   */
  slug?: string | null;
  role: string;
  startDate: string;
  endDate?: string | null;
  current?: boolean | null;
  /**
   * One line. Shown in mosaic cells and homepage strips.
   */
  summary: string;
  /**
   * Short mono tag shown beside the title. Defaults to the first tag.
   */
  subtag?: string | null;
  /**
   * Short uppercase keywords, e.g. RUST, CRYPTO, X3DH.
   */
  tags?: string[] | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Buttons rendered inside the popup card.
   */
  links?:
    | {
        /**
         * e.g. GITHUB, WRITE-UP, LIVE
         */
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  /**
   * Derived from the dates above.
   */
  year?: number | null;
  /**
   * 1–5. Drives tower height in the chamber and ordering everywhere.
   */
  weight: number;
  /**
   * Width of this item inside the CARDS mosaic.
   */
  mosaicSpan?: ('auto' | '2' | '3' | '4') | null;
  /**
   * Show in this section's homepage card strip.
   */
  featured?: boolean | null;
  featuredOrder?: number | null;
  /**
   * Unpublished items are hidden from the public site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  title: string;
  /**
   * Leave blank to derive from the title.
   */
  slug?: string | null;
  issuer: string;
  /**
   * e.g. 1ST PLACE, FINALIST, GOLD MEDAL.
   */
  placement?: string | null;
  date: string;
  scope?: ('international' | 'national' | 'regional' | 'university') | null;
  /**
   * One line. Shown in mosaic cells and homepage strips.
   */
  summary: string;
  /**
   * Short mono tag shown beside the title. Defaults to the first tag.
   */
  subtag?: string | null;
  /**
   * Short uppercase keywords, e.g. RUST, CRYPTO, X3DH.
   */
  tags?: string[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Buttons rendered inside the popup card.
   */
  links?:
    | {
        /**
         * e.g. GITHUB, WRITE-UP, LIVE
         */
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  media?: (number | null) | Media;
  /**
   * Derived from the dates above.
   */
  year?: number | null;
  /**
   * 1–5. Drives tower height in the chamber and ordering everywhere.
   */
  weight: number;
  /**
   * Width of this item inside the CARDS mosaic.
   */
  mosaicSpan?: ('auto' | '2' | '3' | '4') | null;
  /**
   * Show in this section's homepage card strip.
   */
  featured?: boolean | null;
  featuredOrder?: number | null;
  /**
   * Unpublished items are hidden from the public site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One entry per event. Challenges attach to these.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ctf-competitions".
 */
export interface CtfCompetition {
  id: number;
  title: string;
  /**
   * Leave blank to derive from the title.
   */
  slug?: string | null;
  organizer: string;
  team?: string | null;
  date: string;
  /**
   * e.g. 3RD / 412 TEAMS. Leave blank if not placed.
   */
  placement?: string | null;
  format?: ('jeopardy' | 'attack-defense' | 'koth' | 'mixed') | null;
  /**
   * One line. Shown in mosaic cells and homepage strips.
   */
  summary: string;
  /**
   * Short mono tag shown beside the title. Defaults to the first tag.
   */
  subtag?: string | null;
  /**
   * Short uppercase keywords, e.g. RUST, CRYPTO, X3DH.
   */
  tags?: string[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Buttons rendered inside the popup card.
   */
  links?:
    | {
        /**
         * e.g. GITHUB, WRITE-UP, LIVE
         */
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  year?: number | null;
  /**
   * 1-5. Orders the competition mosaic.
   */
  weight?: number | null;
  /**
   * Unpublished items are hidden from the public site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ctf-challenges".
 */
export interface CtfChallenge {
  id: number;
  title: string;
  /**
   * Leave blank to derive from the title.
   */
  slug?: string | null;
  competition: number | CtfCompetition;
  /**
   * Which side of the board.
   */
  mode: 'solved' | 'authored';
  category:
    'web' | 'crypto' | 'pwn' | 'reverse' | 'forensics' | 'osint' | 'steganography' | 'hardware' | 'blockchain' | 'misc';
  difficulty: 'easy' | 'medium' | 'hard' | 'insane';
  points?: number | null;
  /**
   * How many teams solved it. Authored challenges only.
   */
  solves?: number | null;
  /**
   * One line shown in the challenge row.
   */
  summary?: string | null;
  /**
   * Short uppercase keywords, e.g. RUST, CRYPTO, X3DH.
   */
  tags?: string[] | null;
  /**
   * Write-up body. Loaded lazily when the popup opens.
   */
  writeup?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Off-site write-up or source.
   */
  externalUrl?: string | null;
  attachments?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Unpublished items are hidden from the public site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'ctf-competitions';
        value: number | CtfCompetition;
      } | null)
    | ({
        relationTo: 'ctf-challenges';
        value: number | CtfChallenge;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  category?: T;
  date?: T;
  year?: T;
  subtag?: T;
  tags?: T;
  description?: T;
  repoUrl?: T;
  liveUrl?: T;
  role?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  screenshot?: T;
  stripArtwork?: T;
  weight?: T;
  mosaicSpan?: T;
  featured?: T;
  featuredOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  organization?: T;
  location?: T;
  startDate?: T;
  endDate?: T;
  current?: T;
  employmentType?: T;
  summary?: T;
  subtag?: T;
  tags?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  description?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  logo?: T;
  year?: T;
  weight?: T;
  mosaicSpan?: T;
  featured?: T;
  featuredOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  role?: T;
  startDate?: T;
  endDate?: T;
  current?: T;
  summary?: T;
  subtag?: T;
  tags?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  description?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  logo?: T;
  year?: T;
  weight?: T;
  mosaicSpan?: T;
  featured?: T;
  featuredOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  issuer?: T;
  placement?: T;
  date?: T;
  scope?: T;
  summary?: T;
  subtag?: T;
  tags?: T;
  description?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  media?: T;
  year?: T;
  weight?: T;
  mosaicSpan?: T;
  featured?: T;
  featuredOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ctf-competitions_select".
 */
export interface CtfCompetitionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  organizer?: T;
  team?: T;
  date?: T;
  placement?: T;
  format?: T;
  summary?: T;
  subtag?: T;
  tags?: T;
  description?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  logo?: T;
  year?: T;
  weight?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ctf-challenges_select".
 */
export interface CtfChallengesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  competition?: T;
  mode?: T;
  category?: T;
  difficulty?: T;
  points?: T;
  solves?: T;
  summary?: T;
  tags?: T;
  writeup?: T;
  externalUrl?: T;
  attachments?:
    | T
    | {
        file?: T;
        id?: T;
      };
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Everything the site says about you outside the survey collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: number;
  name: string;
  /**
   * Used in the OG image and tab title.
   */
  initials?: string | null;
  /**
   * First hero line, solid ink.
   */
  heroLineOne: string;
  /**
   * Second hero line, outlined cyan stroke.
   */
  heroLineTwo: string;
  /**
   * The one word in the hero drawn as an outlined cyan stroke. Must appear in one of the two lines above.
   */
  heroAccentWord?: string | null;
  /**
   * The paragraph under the hero.
   */
  tagline: string;
  /**
   * Short role line for metadata and the OG image.
   */
  role?: string | null;
  portrait?: (number | null) | Media;
  /**
   * Lead paragraph of the homepage About chapter, set larger than the body.
   */
  aboutIntro?: string | null;
  /**
   * The rest of the About chapter, under the lead paragraph.
   */
  about?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The connected strip inside the homepage About chapter.
   */
  focusAreas?:
    | {
        title: string;
        body: string;
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        group: string;
        items: string[];
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        institution: string;
        program: string;
        period: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  email: string;
  location?: string | null;
  /**
   * Mono string in the footer.
   */
  coordinates?: string | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Link used by the [CV] item in the navbar. Overrides the upload below.
   */
  cvUrl?: string | null;
  cvFile?: (number | null) | Media;
  siteTitle?: string | null;
  siteDescription?: string | null;
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  name?: T;
  initials?: T;
  heroLineOne?: T;
  heroLineTwo?: T;
  heroAccentWord?: T;
  tagline?: T;
  role?: T;
  portrait?: T;
  aboutIntro?: T;
  about?: T;
  focusAreas?:
    | T
    | {
        title?: T;
        body?: T;
        tag?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        group?: T;
        items?: T;
        id?: T;
      };
  education?:
    | T
    | {
        institution?: T;
        program?: T;
        period?: T;
        detail?: T;
        id?: T;
      };
  email?: T;
  location?: T;
  coordinates?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  cvUrl?: T;
  cvFile?: T;
  siteTitle?: T;
  siteDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}